FROM python:3

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY Testing/. . ./


RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

USER docker

CMD python code/test_main.py
