# build environment
FROM node:16-alpine3.14 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY Front-End/package.json ./
COPY Front-End/package-lock.json ./


RUN npm ci --production
COPY . . ./
RUN npm run start

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# to make react-router work with nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
