# Sign up and verification page ids
sign_up_with_email_button_id = 'signup-email-button'
signup_name_textbox_id = 'name'
signup_email_textbox_id = 'email'
signup_month_list_id = 'month'
signup_day_list_id = 'day'
signup_year_list_id = 'year'
signup_next_button_id = 'next-button'
signup_close_button = '#signup-modals > div > div > div:nth-child(1) > button > svg'
signup_name_error = 'sign-up-name-error'
signup_email_error = 'sign-up-email-error'
invalid_email_error = '#signup-modals > div > form > div.StepOne_body__woi2M > label:nth-child(2) > p'
verification_page_title = '#signup-modals > div > div.start-modals-title-container > h1'
verification_code_textbox_id = 'verificationCode'
verification_page_next_button = 'signup-submit-verification-code'
incorrect_verification_code_1 = '123456'
incorrect_verification_error = 'sign-up-verify-error'
incorrect_verification_error_1 = 'sign-up-verify-error'
incorrect_verification_error_2 = 'sign-up-verify-error'
incorrect_verification_code_3 = 'fjijefiojioeuwuiueiorijfkdjscxnjchdufhioepj'
password_page_title_class_name = 'StepPassword_title__7Ciya'
password_page_password_textbox = 'password'
password_page_next_button = 'Signup-submit-password'
username_page_username_textbox = 'username'
username_page_next_button = 'signup-submit-username'
email_already_registered_error = 'sign-up-email-error'

# fetching correct verification codes IDs
gmail_url = 'https://www.gmail.com'
gmail_sign_in_button_css_selector = 'body > header > div > div > div > a.button.button--medium.button--mobile-before-hero-only'
gmail_email_textbox_id = 'identifierId'
gmail_next_button_css_selector = '#identifierNext > div > button > span'
gmail_password_textbox_css_selector = '#password > div.aCsJod.oJeWuf > div > div.Xb9hP > input'
gmail_password_next_button_css_selector = '#passwordNext > div > button > span'
gmail_email = 'whisptesting@gmail.com'
gmail_password = 'This,is,purely,for,testing'
gmail_first_email_in_inbox_id = ':28'
whisp_verification_email_text_class_name = 'a3s aiL'

# sign in page ids
sample_username = '@testusername'
sample_email = 'test_email@gmail.com'
sign_in_button_id = 'signin-button'
sign_in_email_textbox_id = 'login-email'
sign_in_next_button = 'next-button'
sign_in_password_textbox_id = 'password'
sign_in_login_button_id = 'next-login-password-button'
sign_in_invalid_password = 'jdslaoeury'
sign_in_invalid_password_error = 'login-password-error'
home_page_element = '#root > div > div > div.Foundation_outlet__xuP5Z > div > div.Home_home-header__42gWJ > h2'
log_out_button = '#root > div > div > div:nth-child(1) > div > div > div.Foundation_user-menu__2kSmD'
empty_username_error = 'login-emailor-username-error'
empty_password_error = 'login-password-error'

# Forgot password page ids
forgot_password_button = 'login-forgot-password-button'
forgot_password_textbox_id = 'Find-Twitter-account-emailOrUsername'
forgot_password_search_button_id = 'search-email-button'
user_not_found_error = 'forgot-password-emailor-username-error'

# Home page ids
sample_text = 'this is a test done by testing team'
text_exceed_limit = 'limitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimitlimit'
tweet_box_id = 'twbox-text-area-home'
whisp_button_id = 'twbox-submit'
select_image_button = '#Tweet-box > div > div > div.TweetBox_text-area-icons__JlZNF > div.TweetBox_media-icons__Glmzm > div:nth-child(1) > svg'
post_body_class_name = 'Post_postbody__oRteY'
image_1_css_selector = "img[src$='imageabcde1.png']"
image_2_css_selector = "img[src$='imagefghi2.png']"
image_3_css_selector = "img[src$='imagejklm3.png']"
image_4_css_selector = "img[src$='imagenopq4.png']"
image_5_css_selector = "img[src$='imagerstu5.png']"
images_in_tweetbox_id = 'image-box-image-canvas'
feed_page_id = 'feed'

# Profile
profile_navbar = 'profile'
profile_edit_button = 'edit_profile'
profile_name_textbox = 'name'
profile_bio_textbox = 'bio'
profile_save_changes = 'save-changes'
profile_name_error_limitation = 'name-error'
profile_close_edit = 'close'
profile_discard_changes = 'discard-changes'
profile_add_photo_cover = 'add-cover'
profile_add_photo_profile = 'add-profile'
profile_apply_photo = 'apply'
profile_photo_open = 'photo'
profile_cover_open = 'cover'
profile_remove_cover_photo = 'remove-cover'

# SETTINGS
Settings_navbar = 'Settings'
Settings_account_info = 'account-info'
Settings_change_password = 'change-password'
Settings_current_password = 'current-password'
Settings_new_password = 'new-password'
Settings_confirm_password = 'confirm-password'
Settings_confirm_password_error = 'confirm-error'
Settings_save_pass_change = 'save-password'
Settings_password_error = 'invalid-password'

# Bookmarks
bookmarks_option_id = 'add-remove-bookmarks'
bookmarks_navbar_button = '#Bookmarks > div > p'
bookmark_remove_tweet_id = 'add-remove-bookmarks'
bookmark_tweet_body = '#post > div > div:nth-child(2) > div:nth-child(1)'
bookmark_share_button_on_page = '#post > div > div:nth-child(3) > div > button > svg'

# Admin
admin_block_button_id = 'followbutton'
admin_unblock_button_id = 'followbutton'
admin_first_account_shown = '#admin-foundation > div.AdminUsers_admin-users__ifX2F > div.UsersFeed_notifeed__Y\+Pcx > div > div:nth-child(1) > div.User_text-container__\+qAfN > b'
admin_month_id = 'month'
admin_day_id = 'day'
admin_year_id = 'year'
admin_invalid_date_error = '#popup-page-children > div > b.AdminUsers_unblock-popup-error-message__KBYEc'
admin_block_page_button = '#popup-page-children > div > button'
admin_blocked_users_button = '#blocked-users > div > p'
admin_users_button = '#users > div > p'
admin_search_bar = 'searchbar-input-element'
admin_homepage_test = 'twbox-text-area-home'
delete_user_email = 'whisptesting2@gmail.com'
delete_user_password = 'BnSuliman@1'
delete_user_username = '@whisptesting'
admin_account_select = '#admin-foundation > div.AdminUsers_admin-users__ifX2F > div.UsersFeed_notifeed__Y\+Pcx > div > div:nth-child(1) > div.User_text-container__\+qAfN > b'
admin_confirm_delete = '#popup-page-children > div > div.AdminUsers_buttons-container__0Pixg > button.AdminUsers_delete-button__xKPcY'
admin_cancel_delete = '#popup-page-children > div > div.AdminUsers_buttons-container__0Pixg > button.AdminUsers_cancel-button__wW-iB'
admin_error_in_sign = 'login-password-error'
admin_no_result_found_element = '#admin-foundation > div.AdminUsers_admin-users__ifX2F > b'

# notification
user_1_username = '@YasmeenZaki13'
user_1_password = 'BnSuliman@1'
user_2_username = '@mernayoussef'
user_2_password = 'BnSuliman@1'
notifications_log_out_button = '#root > div > div > div:nth-child(1) > div > div > div.Foundation_user-menu__k3jLR > div'
notification_tweet_body = '#root > div > div > div.Foundation_outlet__QoH\+\+ > div > div > div > div > button:nth-child(3) > div.NotiContent_display-name__aaNX8'
like_tweet_button = '#post > div > div:nth-child(3) > div > div:nth-child(3) > button > svg'
retweet_button = '#post > div > div:nth-child(3) > div > div:nth-child(2) > button > svg'
reply_tweet_button = '#post > div > div:nth-child(3) > div > div:nth-child(1) > svg'
notification_page_on_navbar = '#Notifications > div'
homepage_on_navbar = '#Home > div'

chrome_driver = 'E:\Sem 6\Software Engineering\Whisper\Testing\drivers\chromedriver.exe'
# chrome_driver = "..\drivers\chromedriver.exe"
email = 'testingwhisper2@gmail.com'
password = 'BnSuliman@1'
username = '@YasmeenZaki13'
admin_username = 'adminUser'
admin_password = '12345#Aa'

# chrome_driver = 'E:\Sem 6\Software Engineering\Whisper\Testing\drivers\chromedriver.exe'
# chrome_driver = "D:\Whisper-Testing\Testing\code\drivers/chromedriver.exe"
