sign_up_with_email_button_id = 'signup-email-button'
signup_name_textbox_id = '#name'
signup_email_textbox_id = 'email'
signup_month_list_id = 'month'
signup_day_list_id = 'day'
signup_year_list_id = 'year'
signup_next_button_id = 'next-button'
signup_close_button = '#signup-modals > div > div > div:nth-child(1) > button'
signup_name_error='//*[@id="signup-modals"]/div/form/div[1]/p'
signup_email_error='//*[@id="signup-modals"]/div/form/div[1]/label[2]/p'
#signup_name_error = '#signup-modals > div > form > div.StepOne_body__qklkQ > p'
#signup_email_error = '#signup-modals > div > form > div.StepOne_body__qklkQ > label:nth-child(3) > p'

chrome_driver = '/chromedriver/chromedriver'
