import test_signup

test_signup.test_signup_invalid_email_and_name()
test_signup.test_signup_invalid_email_only()
test_signup.test_signup_invalid_name_only()
test_signup.test_signup_invalid_date_only()
test_signup.test_signup_valid_date_only()
test_signup.test_signup_valid_date_and_name()
test_signup.test_signup_valid_date_and_email()
print('SIGN_UP_TESTS_DONE')
